### ISSUE TITLE
UI3: Math works incorrectly

### ISSUE THREAD

**Issue by mattersmap** [hyperc-ai/hyperc#406]
If i run this project 
[loan back 5 incorrect solution . xtj.txt](https://github.com/criticalhop/hyperc/files/5978572/loan.back.5.incorrect.solution.xtj.txt)

with these configs:
```
 HYPERC_TEMPDIR=/home/artem/repo/out HYPERC_SEARCH_CONFIG=lmcount_alt5 HYPERC_LVER_MAX_TIME=0 HYPERC_STORE_STDOUT=0 PYTHON=pypy3 HYPERC_NEW_OBJECTS=2 HYPERC_SOLVER_MAX_TIME=9000 HYPERC_SPLIT_SKIP=3 DOWNWARD_TOTAL_PUSHES=500000000 HYPERC_RTX_OFF=1 FLASK_RUN_HOST=0.0.0.0 HYPERC_MAX_PROC=1 HYPERC_ENABLE_SIDEADD=0 HYPERC_MAX_EFFECT_AMOUNT=3  FLASK_RUN_PORT=5057 HYPERC_RTX_OFF=1  flask run
```

I get this result: 
![image](https://user-images.githubusercontent.com/36539458/107889703-7c035b80-6f25-11eb-9895-ac4a808fba56.png)

so in log I see sum of  field C equal to 16 but it all goest to the field B2 in dashboard and it is limited by A2 value  ( equal to 10 ) 

and I see that line of csv in which D field is equal  to 0 after first line in the plan  are  again used in lines 3 and 4

 And it looks like it is able to take lines that have zero  and decrement them 

added check D1>0 and it started to solve well - we have some issue here
[loan back 6 correct solution . xtj.txt](https://github.com/criticalhop/hyperc/files/5978637/loan.back.6.correct.solution.xtj.txt)

**Comment by romaeee** [comment]
Irrelevant
