### ISSUE TITLE
AssertionError: Function <class 'tests.test_sets.IntSetTest'> has missing annotations [], ['optional']

### ISSUE THREAD

**Issue by dmytro-terletskyi** [hyperc-ai/hyperc#447]
When you clone the [hyperc](https://github.com/criticalhop/hyperc), then perform
```
git checkout develop
```
then run
```
pip install .
```
then run
```
HYPERC_USE_CACHE=0 HYPERC_SPLIT_OFF=1 HYPERC_STORE_STDOUT=1 HYPERC_SOLVER_MAX_TIME=900 HYPERC_TEMPDIR=./tmp HYPERC_SEARCH_CONFIG=lmcount_alt5 HYPERC_MAX_PROC=1 PYTHON=pypy3 pytest
```
some tests are fall

![11](https://user-images.githubusercontent.com/74676672/116077064-b6b00f80-a69d-11eb-9eb3-2b946dda09f7.png)

the test **tests/test_x_splitter_perf.py** executes more than 10 minutes when you stop the test execution you obtain the error message **AssertionError: Function <class 'tests.test_sets.IntSetTest'> has missing annotations [], ['optional']** and the following stack traces

![12](https://user-images.githubusercontent.com/74676672/116077071-b748a600-a69d-11eb-8a31-d2bc4c727a96.png)
![13](https://user-images.githubusercontent.com/74676672/116077072-b7e13c80-a69d-11eb-8e72-4632788ebe50.png)
![14](https://user-images.githubusercontent.com/74676672/116077076-b879d300-a69d-11eb-8054-b07befdb3de6.png)
![15](https://user-images.githubusercontent.com/74676672/116077077-b9126980-a69d-11eb-8780-284c48744153.png)
![16](https://user-images.githubusercontent.com/74676672/116077080-b9ab0000-a69d-11eb-8a48-eb3191826263.png)

This bug is probably connected with #446

**Comment by dmytro-terletskyi** [comment]
![Screenshot_20211104_155115](https://user-images.githubusercontent.com/74676672/140325811-96748352-fa84-4bc8-91c7-b432fa1a0957.png)
![Screenshot_20211104_155131](https://user-images.githubusercontent.com/74676672/140325821-5c118085-0318-4225-af0c-5939eb134c4a.png)

**Comment by dmytro-terletskyi** [comment]
after change

**Comment by dmytro-terletskyi** [comment]
Using master branch

![Screenshot_20211104_195022](https://user-images.githubusercontent.com/74676672/140392959-7027bddb-c10c-4da0-b2f3-83e461cd0ff8.png)
![Screenshot_20211104_195035](https://user-images.githubusercontent.com/74676672/140392967-e42c0f04-b5e9-483d-b9c9-1b9a3773b2e7.png)
![Screenshot_20211104_195048](https://user-images.githubusercontent.com/74676672/140392971-84edc2d3-538d-406d-86fb-7e019bda4840.png)
![Screenshot_20211104_195059](https://user-images.githubusercontent.com/74676672/140392975-b3b3bae7-f52f-4ee9-8e04-8f26f0a486b1.png)
![Screenshot_20211104_195112](https://user-images.githubusercontent.com/74676672/140392977-0022111e-2a4c-4d05-8992-ca42be4b22cd.png)

**Comment by romaeee** [comment]
closed according to comment
